name: bot-binance
channels:
  - conda-forge
dependencies:
  - python=3.9.*
  - pandas=1.3.*
  - numpy=1.21.*
  - matplotlib=3.4.*
  - websockets=10.1.*
  - asyncio=3.10.*
  - pip=21.3.*
  - pip:
    - python-binance==1.0.*
